
var __cov_ASXtRTi1BjDuDZBXdjJSSg = (Function('return this'))();
if (!__cov_ASXtRTi1BjDuDZBXdjJSSg.__coverage__) { __cov_ASXtRTi1BjDuDZBXdjJSSg.__coverage__ = {}; }
__cov_ASXtRTi1BjDuDZBXdjJSSg = __cov_ASXtRTi1BjDuDZBXdjJSSg.__coverage__;
if (!(__cov_ASXtRTi1BjDuDZBXdjJSSg['E:\\Training-Codes\\jasmine\\test2\\source\\calculator.js'])) {
   __cov_ASXtRTi1BjDuDZBXdjJSSg['E:\\Training-Codes\\jasmine\\test2\\source\\calculator.js'] = {"path":"E:\\Training-Codes\\jasmine\\test2\\source\\calculator.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0},"b":{"1":[0,0],"2":[0,0],"3":[0,0],"4":[0,0]},"f":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0},"fnMap":{"1":{"name":"(anonymous_1)","line":2,"loc":{"start":{"line":2,"column":7},"end":{"line":2,"column":22}}},"2":{"name":"(anonymous_2)","line":5,"loc":{"start":{"line":5,"column":12},"end":{"line":5,"column":27}}},"3":{"name":"(anonymous_3)","line":8,"loc":{"start":{"line":8,"column":12},"end":{"line":8,"column":27}}},"4":{"name":"(anonymous_4)","line":11,"loc":{"start":{"line":11,"column":10},"end":{"line":11,"column":25}}},"5":{"name":"(anonymous_5)","line":18,"loc":{"start":{"line":18,"column":11},"end":{"line":18,"column":24}}},"6":{"name":"(anonymous_6)","line":22,"loc":{"start":{"line":22,"column":13},"end":{"line":22,"column":24}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":34,"column":2}},"2":{"start":{"line":3,"column":4},"end":{"line":3,"column":17}},"3":{"start":{"line":6,"column":4},"end":{"line":6,"column":17}},"4":{"start":{"line":9,"column":4},"end":{"line":9,"column":17}},"5":{"start":{"line":12,"column":4},"end":{"line":15,"column":5}},"6":{"start":{"line":14,"column":6},"end":{"line":14,"column":47}},"7":{"start":{"line":16,"column":4},"end":{"line":16,"column":17}},"8":{"start":{"line":19,"column":4},"end":{"line":19,"column":19}},"9":{"start":{"line":24,"column":4},"end":{"line":30,"column":5}},"10":{"start":{"line":25,"column":6},"end":{"line":25,"column":68}},"11":{"start":{"line":26,"column":11},"end":{"line":30,"column":5}},"12":{"start":{"line":27,"column":6},"end":{"line":27,"column":15}},"13":{"start":{"line":29,"column":6},"end":{"line":29,"column":36}},"14":{"start":{"line":36,"column":0},"end":{"line":36,"column":28}}},"branchMap":{"1":{"line":12,"type":"if","locations":[{"start":{"line":12,"column":4},"end":{"line":12,"column":4}},{"start":{"line":12,"column":4},"end":{"line":12,"column":4}}]},"2":{"line":24,"type":"if","locations":[{"start":{"line":24,"column":4},"end":{"line":24,"column":4}},{"start":{"line":24,"column":4},"end":{"line":24,"column":4}}]},"3":{"line":26,"type":"if","locations":[{"start":{"line":26,"column":11},"end":{"line":26,"column":11}},{"start":{"line":26,"column":11},"end":{"line":26,"column":11}}]},"4":{"line":26,"type":"binary-expr","locations":[{"start":{"line":26,"column":15},"end":{"line":26,"column":19}},{"start":{"line":26,"column":23},"end":{"line":26,"column":27}}]}}};
}
__cov_ASXtRTi1BjDuDZBXdjJSSg = __cov_ASXtRTi1BjDuDZBXdjJSSg['E:\\Training-Codes\\jasmine\\test2\\source\\calculator.js'];
__cov_ASXtRTi1BjDuDZBXdjJSSg.s['1']++;const Calculator={add:function(a,b){__cov_ASXtRTi1BjDuDZBXdjJSSg.f['1']++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['2']++;return a+b;},subtract:function(a,b){__cov_ASXtRTi1BjDuDZBXdjJSSg.f['2']++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['3']++;return a-b;},multiply:function(a,b){__cov_ASXtRTi1BjDuDZBXdjJSSg.f['3']++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['4']++;return a*b;},divide:function(a,b){__cov_ASXtRTi1BjDuDZBXdjJSSg.f['4']++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['5']++;if(b===0){__cov_ASXtRTi1BjDuDZBXdjJSSg.b['1'][0]++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['6']++;throw new Error('Cannot divide by zero');}else{__cov_ASXtRTi1BjDuDZBXdjJSSg.b['1'][1]++;}__cov_ASXtRTi1BjDuDZBXdjJSSg.s['7']++;return a/b;},average:function(a,b){__cov_ASXtRTi1BjDuDZBXdjJSSg.f['5']++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['8']++;return(a+b)/2;},factorial:function(a){__cov_ASXtRTi1BjDuDZBXdjJSSg.f['6']++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['9']++;if(a<0){__cov_ASXtRTi1BjDuDZBXdjJSSg.b['2'][0]++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['10']++;throw new Error('There is no factorial for negative Numbers');}else{__cov_ASXtRTi1BjDuDZBXdjJSSg.b['2'][1]++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['11']++;if((__cov_ASXtRTi1BjDuDZBXdjJSSg.b['4'][0]++,a==1)||(__cov_ASXtRTi1BjDuDZBXdjJSSg.b['4'][1]++,a==0)){__cov_ASXtRTi1BjDuDZBXdjJSSg.b['3'][0]++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['12']++;return 1;}else{__cov_ASXtRTi1BjDuDZBXdjJSSg.b['3'][1]++;__cov_ASXtRTi1BjDuDZBXdjJSSg.s['13']++;return a*this.factorial(a-1);}}}};__cov_ASXtRTi1BjDuDZBXdjJSSg.s['14']++;module.exports=Calculator;
